export const PORT = process.env.PORT || 80;
export const POOL_INTERVAL = parseInt(process.env.POOL_INTERVAL) || 5000;
export const ARCHIVE_PATH = '/archive';
export const AUTH_URL = process.env.AUTH_URL || 'http://asdfasdf';
export const YOUTUBE_HOST = process.env.YOUTUBE_HOST || 'http://youtube';
export const DOWNLOAD_FOLDER = '/archive/Musics/download';
export const BACKEND_HOST = process.env.BACKEND_HOST || 'http://backend';
export const FFMPEG_SOCKET_PATH = '/socket.io/ffmpeg';
export const YOUTUBE_SOCKET_PATH = '/socket.io/youtube';